version: '3.9'

services:

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: incryiptDB
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432


